# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Documents/py/pyqt5_calc/ui/calc.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(238, 387)
        MainWindow.setStyleSheet("QMainWindow#MainWindow{\n"
"    background-color: rgb(201, 255, 208);;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(4, 3, 231, 31))
        self.output_label.setStyleSheet("border: 1px solid black;\n"
"border-radius: 7px;\n"
"")
        self.output_label.setObjectName("output_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 40, 180, 226))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.five_button = QtWidgets.QPushButton(self.layoutWidget)
        self.five_button.setMinimumSize(QtCore.QSize(40, 40))
        self.five_button.setMaximumSize(QtCore.QSize(40, 40))
        self.five_button.setObjectName("five_button")
        self.gridLayout.addWidget(self.five_button, 1, 1, 1, 1)
        self.zero_button = QtWidgets.QPushButton(self.layoutWidget)
        self.zero_button.setMinimumSize(QtCore.QSize(40, 40))
        self.zero_button.setMaximumSize(QtCore.QSize(40, 40))
        self.zero_button.setObjectName("zero_button")
        self.gridLayout.addWidget(self.zero_button, 3, 1, 1, 1)
        self.one_button = QtWidgets.QPushButton(self.layoutWidget)
        self.one_button.setMinimumSize(QtCore.QSize(40, 40))
        self.one_button.setMaximumSize(QtCore.QSize(40, 40))
        self.one_button.setObjectName("one_button")
        self.gridLayout.addWidget(self.one_button, 0, 0, 1, 1)
        self.power_button = QtWidgets.QPushButton(self.layoutWidget)
        self.power_button.setMinimumSize(QtCore.QSize(40, 40))
        self.power_button.setMaximumSize(QtCore.QSize(40, 40))
        self.power_button.setObjectName("power_button")
        self.gridLayout.addWidget(self.power_button, 3, 0, 1, 1)
        self.two_button = QtWidgets.QPushButton(self.layoutWidget)
        self.two_button.setMinimumSize(QtCore.QSize(40, 40))
        self.two_button.setMaximumSize(QtCore.QSize(40, 40))
        self.two_button.setObjectName("two_button")
        self.gridLayout.addWidget(self.two_button, 0, 1, 1, 1)
        self.clear_button = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_button.setMinimumSize(QtCore.QSize(40, 40))
        self.clear_button.setMaximumSize(QtCore.QSize(40, 40))
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 4, 2, 1, 1)
        self.repeat_button = QtWidgets.QPushButton(self.layoutWidget)
        self.repeat_button.setMinimumSize(QtCore.QSize(40, 40))
        self.repeat_button.setMaximumSize(QtCore.QSize(40, 40))
        self.repeat_button.setObjectName("repeat_button")
        self.gridLayout.addWidget(self.repeat_button, 4, 3, 1, 1)
        self.nine_button = QtWidgets.QPushButton(self.layoutWidget)
        self.nine_button.setMinimumSize(QtCore.QSize(40, 40))
        self.nine_button.setMaximumSize(QtCore.QSize(40, 40))
        self.nine_button.setObjectName("nine_button")
        self.gridLayout.addWidget(self.nine_button, 2, 2, 1, 1)
        self.plus_button = QtWidgets.QPushButton(self.layoutWidget)
        self.plus_button.setMinimumSize(QtCore.QSize(40, 40))
        self.plus_button.setMaximumSize(QtCore.QSize(40, 40))
        self.plus_button.setObjectName("plus_button")
        self.gridLayout.addWidget(self.plus_button, 0, 3, 1, 1)
        self.percent_button = QtWidgets.QPushButton(self.layoutWidget)
        self.percent_button.setMinimumSize(QtCore.QSize(40, 40))
        self.percent_button.setMaximumSize(QtCore.QSize(40, 40))
        self.percent_button.setObjectName("percent_button")
        self.gridLayout.addWidget(self.percent_button, 4, 0, 1, 1)
        self.division_button = QtWidgets.QPushButton(self.layoutWidget)
        self.division_button.setMinimumSize(QtCore.QSize(40, 40))
        self.division_button.setMaximumSize(QtCore.QSize(40, 40))
        self.division_button.setObjectName("division_button")
        self.gridLayout.addWidget(self.division_button, 3, 3, 1, 1)
        self.minus_button = QtWidgets.QPushButton(self.layoutWidget)
        self.minus_button.setMinimumSize(QtCore.QSize(40, 40))
        self.minus_button.setMaximumSize(QtCore.QSize(40, 40))
        self.minus_button.setObjectName("minus_button")
        self.gridLayout.addWidget(self.minus_button, 1, 3, 1, 1)
        self.eight_button = QtWidgets.QPushButton(self.layoutWidget)
        self.eight_button.setMinimumSize(QtCore.QSize(40, 40))
        self.eight_button.setMaximumSize(QtCore.QSize(40, 40))
        self.eight_button.setObjectName("eight_button")
        self.gridLayout.addWidget(self.eight_button, 2, 1, 1, 1)
        self.root_button = QtWidgets.QPushButton(self.layoutWidget)
        self.root_button.setMinimumSize(QtCore.QSize(40, 40))
        self.root_button.setMaximumSize(QtCore.QSize(40, 40))
        self.root_button.setObjectName("root_button")
        self.gridLayout.addWidget(self.root_button, 3, 2, 1, 1)
        self.four_button = QtWidgets.QPushButton(self.layoutWidget)
        self.four_button.setMinimumSize(QtCore.QSize(40, 40))
        self.four_button.setMaximumSize(QtCore.QSize(40, 40))
        self.four_button.setObjectName("four_button")
        self.gridLayout.addWidget(self.four_button, 1, 0, 1, 1)
        self.multy_button = QtWidgets.QPushButton(self.layoutWidget)
        self.multy_button.setMinimumSize(QtCore.QSize(40, 40))
        self.multy_button.setMaximumSize(QtCore.QSize(40, 40))
        self.multy_button.setObjectName("multy_button")
        self.gridLayout.addWidget(self.multy_button, 2, 3, 1, 1)
        self.six_button = QtWidgets.QPushButton(self.layoutWidget)
        self.six_button.setMinimumSize(QtCore.QSize(40, 40))
        self.six_button.setMaximumSize(QtCore.QSize(40, 40))
        self.six_button.setObjectName("six_button")
        self.gridLayout.addWidget(self.six_button, 1, 2, 1, 1)
        self.seven_button = QtWidgets.QPushButton(self.layoutWidget)
        self.seven_button.setMinimumSize(QtCore.QSize(40, 40))
        self.seven_button.setMaximumSize(QtCore.QSize(40, 40))
        self.seven_button.setObjectName("seven_button")
        self.gridLayout.addWidget(self.seven_button, 2, 0, 1, 1)
        self.three_button = QtWidgets.QPushButton(self.layoutWidget)
        self.three_button.setMinimumSize(QtCore.QSize(40, 40))
        self.three_button.setMaximumSize(QtCore.QSize(40, 40))
        self.three_button.setObjectName("three_button")
        self.gridLayout.addWidget(self.three_button, 0, 2, 1, 1)
        self.dot_button = QtWidgets.QPushButton(self.layoutWidget)
        self.dot_button.setMinimumSize(QtCore.QSize(40, 40))
        self.dot_button.setMaximumSize(QtCore.QSize(40, 40))
        self.dot_button.setObjectName("dot_button")
        self.gridLayout.addWidget(self.dot_button, 4, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 40, 42, 226))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.backspace_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.backspace_button.setMinimumSize(QtCore.QSize(40, 40))
        self.backspace_button.setMaximumSize(QtCore.QSize(40, 40))
        self.backspace_button.setObjectName("backspace_button")
        self.gridLayout_2.addWidget(self.backspace_button, 1, 0, 1, 1)
        self.sbrack_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.sbrack_button.setMinimumSize(QtCore.QSize(40, 40))
        self.sbrack_button.setMaximumSize(QtCore.QSize(40, 40))
        self.sbrack_button.setObjectName("sbrack_button")
        self.gridLayout_2.addWidget(self.sbrack_button, 3, 0, 1, 1)
        self.fact_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.fact_button.setMinimumSize(QtCore.QSize(40, 40))
        self.fact_button.setMaximumSize(QtCore.QSize(40, 40))
        self.fact_button.setObjectName("fact_button")
        self.gridLayout_2.addWidget(self.fact_button, 6, 0, 1, 1)
        self.fbrack_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.fbrack_button.setMinimumSize(QtCore.QSize(40, 40))
        self.fbrack_button.setMaximumSize(QtCore.QSize(40, 40))
        self.fbrack_button.setObjectName("fbrack_button")
        self.gridLayout_2.addWidget(self.fbrack_button, 2, 0, 1, 1)
        self.equal_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.equal_button.setMinimumSize(QtCore.QSize(40, 40))
        self.equal_button.setMaximumSize(QtCore.QSize(40, 40))
        self.equal_button.setObjectName("equal_button")
        self.gridLayout_2.addWidget(self.equal_button, 7, 0, 1, 1)
        self.previous_list = QtWidgets.QListWidget(self.centralwidget)
        self.previous_list.setGeometry(QtCore.QRect(4, 270, 231, 111))
        self.previous_list.setStyleSheet("")
        self.previous_list.setObjectName("previous_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 238, 20))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.output_label.setText(_translate("MainWindow", "0"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.power_button.setText(_translate("MainWindow", "x^y"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.repeat_button.setText(_translate("MainWindow", "↺"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.root_button.setText(_translate("MainWindow", "x√y"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.multy_button.setText(_translate("MainWindow", "*"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.dot_button.setText(_translate("MainWindow", "."))
        self.backspace_button.setText(_translate("MainWindow", "⌫"))
        self.sbrack_button.setText(_translate("MainWindow", ")"))
        self.fact_button.setText(_translate("MainWindow", "x!"))
        self.fbrack_button.setText(_translate("MainWindow", "("))
        self.equal_button.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
